### ISSUE TITLE
fastrelease_changelog not working

### ISSUE THREAD

**Issue by PabloRMira** [fastai/fastrelease#40]
First of all, thank you very much for the development of this and all the fantastic fastai ecosystem!

I just got a problem after installation. I wanted to test `fastrelease_changelog` but it didn't work for me. I got the following error:

```python
fastrelease_changelog
Traceback (most recent call last):
  File "/home/pablo/miniconda3/envs/sql-formatter-dev/bin/fastrelease_changelog", line 8, in <module>
    sys.exit(fastrelease_changelog())
  File "/home/pablo/miniconda3/envs/sql-formatter-dev/lib/python3.7/site-packages/fastcore/script.py", line 102, in _f
    tfunc(**merge(args, args_from_prog(func, xtra)))
  File "/home/pablo/miniconda3/envs/sql-formatter-dev/lib/python3.7/site-packages/fastrelease/core.py", line 101, in fastrelease_changelog
    FastRelease().changelog(debug=debug)
  File "/home/pablo/miniconda3/envs/sql-formatter-dev/lib/python3.7/site-packages/fastrelease/core.py", line 61, in __init__
    self.gh = GhApi(owner, repo, token)
NameError: name 'GhApi' is not defined
```

I installed `fastrelease` via pip. I'm using version 0.1.2 in a conda environment

Output of `conda list | grep fastrelease`
```bash
fastrelease               0.1.2                    pypi_0    pypi
```

Could you please help me on this?

Thank you in advance!

**Comment by ayasyrev** [comment]
Got same error.
Its because of wrong import.
Instead of  
from ghapi import * 
should be from ghapi.all import *  
Its solve this error, but next is out:
name 'loads' is not defined --> in ghapi/actions.py
Its can be solved by importing and installing:
from jsonref import loads 
But next error is:
name 'str_enum' is not defined
in: ghapi/actions.py

So problem is in imports and requirements

**Comment by jph00** [comment]
I believe this should be working now - feel free to reopen if you still have the issue above.
