### ISSUE TITLE
fastrelease IOError not showing information

### ISSUE THREAD

**Issue by josiahls** [fastai/fastrelease#46]
I am trying to do a conda release, but the build error isnt showing very much detail. I think this line would fix this:
`run(f"conda {build} --no-anaconda-upload {build_args} {name}", stderr=True)` at [this line](https://github.com/fastai/fastrelease/blob/56c21da0d35d69e8a6d1bf20167af60f94285484/fastrelease/conda.py#L166)
Or we can have the `fastrelease_conda_package` command allow for verbose outputs? I think the previous idea seems better since if a cli command fails (and it will) having the error output would be nice.

```bash
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Traceback (most recent call last):
  File "/usr/share/miniconda/bin/fastrelease_conda_package", line 10, in <module>
    sys.exit(fastrelease_conda_package())
  File "/usr/share/miniconda/lib/python3.8/site-packages/fastcore/script.py", line 105, in _f
    tfunc(**merge(args, args_from_prog(func, xtra)))
  File "/usr/share/miniconda/lib/python3.8/site-packages/fastrelease/conda.py", line 168, in fastrelease_conda_package
    res = run(f"conda {build} --no-anaconda-upload {build_args} {name}")
  File "/usr/share/miniconda/lib/python3.8/site-packages/fastcore/xtras.py", line 174, in run
    if res.returncode: raise IOError(stdout)
OSError
Error: Process completed with exit code 1.
```

**Comment by noklam** [comment]
@josiahls  Did u solve this error? I encounter the same thing
