### ISSUE TITLE
Exception when making a release: Unprocessable Entity

### ISSUE THREAD

**Issue by oguiza** [fastai/fastrelease#71]
I have a library (timeseriesAI/tsai) and I'm trying to create my first release. 

I've generate the token, and created a token file following the instruction in the web. 

fastrelease_changelog works fine. I've modified the CHANGELOG.md file, git add . and git commit. All good.

The issue is when I try fastrelease_release (or fastrelease). I get this error message: 

```
(py37) ➜  tsai git:(main) fastrelease_release
Traceback (most recent call last):
  File "/Users/nacho/anaconda3/envs/py37/bin/fastrelease_release", line 8, in <module>
    sys.exit(fastrelease_release())
  File "/Users/nacho/anaconda3/envs/py37/lib/python3.7/site-packages/fastcore/script.py", line 107, in _f
    tfunc(**merge(args, args_from_prog(func, xtra)))
  File "/Users/nacho/anaconda3/envs/py37/lib/python3.7/site-packages/fastrelease/core.py", line 103, in fastrelease_release
    ver = FastRelease(token=token).release()
  File "/Users/nacho/anaconda3/envs/py37/lib/python3.7/site-packages/fastrelease/core.py", line 83, in release
    self.gh.create_release(ver, body=notes)
  File "/Users/nacho/anaconda3/envs/py37/lib/python3.7/site-packages/ghapi/core.py", line 168, in create_release
    draft=draft, prerelease=prerelease)
  File "/Users/nacho/anaconda3/envs/py37/lib/python3.7/site-packages/ghapi/core.py", line 63, in __call__
    return self.client(self.path, self.verb, headers=headers, route=route_p, query=query_p, data=data_p)
  File "/Users/nacho/anaconda3/envs/py37/lib/python3.7/site-packages/ghapi/core.py", line 109, in __call__
    route=route or None, query=query or None, data=data or None)
  File "/Users/nacho/anaconda3/envs/py37/lib/python3.7/site-packages/fastcore/net.py", line 212, in urlsend
    return urlread(req, return_json=return_json, return_headers=return_headers)
  File "/Users/nacho/anaconda3/envs/py37/lib/python3.7/site-packages/fastcore/net.py", line 113, in urlread
    if 400 <= e.code < 500: raise ExceptionsHTTP[e.code](e.url, e.hdrs, e.fp) from None
fastcore.basics.HTTP422UnprocessableEntityError: HTTP Error 422: Unprocessable Entity
```

I've looked around but couldn't find a solution. Woudl anybody be able to help me?

**Comment by tcapelle** [comment]
I think that this comes from the branch called "main" instead of `master`

**Comment by oguiza** [comment]
Hi @tcapelle, thanks for looking into this. 
I replaced the name since it was recommended by GitHub. So if that was the issue, what is the proposed solution?
The settings.ini file indicates git_url = https://github.com/timeseriesAI/tsai/tree/main/ and branch = main. Is there anything else I need to modify?
